data:
  type: datasets.mnist_cp
  dataset_type: MNIST_CP
  num_workers: 4
  cates: ['0']
  tr_max_sample_points: 800
  te_max_sample_points: 0
  data_dir: data/MNIST-CP
  batch_size: 32
  dataset_scale: 1
  normalize_per_shape: False
  normalize_std_per_axis: False
  recenter_per_shape: True

viz:
  log_freq: 10
  viz_freq: 5000
  save_freq: 100
  val_freq: 100

trainer:
  type: trainers.ae_trainer_3D
  epochs: 100
  seed: 100
  sigma_begin: 1
  sigma_end: 0.01
  sigma_num: 10
  opt_scorenet:
    type: 'adam'
    lr: 1e-3  #  use bs*1e-5/8
    beta1: 0.9
    beta2: 0.999
    momentum: 0.9  # for SGD
    weight_decay: 0.
    scheduler: linear
    step_epoch: 2000
  opt_criticnet:
    type: 'adam'
    lr: 1e-3  #  use bs*1e-5/8
    beta1: 0.9
    beta2: 0.999
    momentum: 0.9  # for SGD
    weight_decay: 0.
    scheduler: linear
    step_epoch: 2000

    
models:
  scorenet:  # [dim] - [hid_dims] - [dim]
    type: models.decoders.resnet_add
    dim: 3
    out_dim: 3
    hidden_size: 256
    n_blocks: 24
    sigma_condition: True
    param_likelihood: False
    xyz_condition: True
    z_dim: 128

inference:
  step_size_ratio: 1
  num_steps: 10
  num_points: 2048
  weight: 1
